import {Payment} from "../../models/index.js"
import {darajaRequest} from "../shared/darajaRequest.js";
import {stkHandlers} from "./stk.handlers.js";
import {generateMpesaPassword} from "../../utils/generateMpesaPassword.js";
import {getMpesaEnvironmentSpecificValue} from "../../utils/getMpesaEnvironmentSpecificValue.js";


/**
 * Response returned by Safaricom Daraja STK Push API.
 *
 * @typedef {Object} DarajaSTKPushResponse
 * @property {string} MerchantRequestID - Unique request identifier generated by the API gateway.
 * @property {string} CheckoutRequestID - Unique checkout request identifier generated by M-PESA.
 * @property {string} ResponseCode - API response code. "0" indicates success.
 * @property {string} ResponseDescription - API response description.
 * @property {string} CustomerMessage - Customer-facing acknowledgment message.
 */

/**
 * Callback payload returned by Safaricom Daraja STK Push callback URL.
 *
 * @typedef {Object} DarajaSTKCallbackPayload
 * @property {Object} Body - Root callback object.
 * @property {Object} Body.stkCallback - STK callback details.
 * @property {string} Body.stkCallback.MerchantRequestID - Original merchant request ID.
 * @property {string} Body.stkCallback.CheckoutRequestID - Original checkout request ID.
 * @property {number} Body.stkCallback.ResultCode - Transaction result code. 0 indicates success.
 * @property {string} Body.stkCallback.ResultDesc - Description of the transaction result.
 * @property {Object} [Body.stkCallback.CallbackMetadata] - Additional transaction metadata returned on success.
 */

/**
 * Initiates an M-Pesa STK Push request.
 *
 * LIPA NA M-PESA ONLINE (M-PESA Express) allows a merchant to initiate
 * a payment request directly to a customer's phone number.
 *
 * The customer receives an STK push prompt on their device and completes
 * the transaction by entering their M-PESA PIN.
 *
 * Notes:
 * - This API is asynchronous.
 * - A successful API response only confirms request acceptance,
 *   not payment completion.
 * - Final transaction status is delivered through the configured callback URL.
 * - Use "CustomerPayBillOnline" for PayBill numbers.
 * - Use "CustomerBuyGoodsOnline" for Till numbers.
 *
 * @param {string} shortCode - Business PayBill or Till number.
 * @param {number} amount - Amount to charge the customer.
 * @param {("CustomerPayBillOnline"|"CustomerBuyGoodsOnline")} transactionType - STK transaction type.
 * @param {string} customerPhone - Customer phone number in format 2547XXXXXXXX.
 * @param {string} [accountRef="CustPay"] - Account reference shown to the customer. Max 12 characters.
 * @param {string} [description="CustSTK"] - Transaction description. Max 13 characters.
 *
 * @returns {Promise<DarajaSTKPushResponse> | stkHandlers}
 */
export const initiateStkPush = async (shortCode, amount, transactionType, customerPhone, accountRef = "CustPay", description = "CustSTK", idempotencyKey, userId) => {
    let payment;
    const timestamp = new Date()
        .toISOString()
        .replace(/[-T:.Z]/g, "")
        .slice(0, 14);

    const url = "/mpesa/stkpush/v1/processrequest"
    const method = "POST"
    const data = {
        "BusinessShortCode": shortCode,
        "Password": generateMpesaPassword(shortCode),
        "Timestamp": timestamp,
        "TransactionType": getMpesaEnvironmentSpecificValue("CustomerPayBillOnline", transactionType),
        "Amount": Number(amount),
        "PartyA": customerPhone,
        "PartyB": Number(shortCode),
        "PhoneNumber": customerPhone,
        "CallBackURL": getMpesaEnvironmentSpecificValue("https://mydomain.com/path", "https://custom.domain.com"),
        "AccountReference": accountRef,
        "TransactionDesc": description,
    }

    const persistedPayload = {
        ...data, "Password": "[REDACTED]"
    }

    try {
        payment = await Payment.create({
            reference: accountRef,
            type: "STK",
            idempotencyKey: idempotencyKey,
            status: "PENDING",
            amount: Number(amount),
            phoneNumber: customerPhone,
            partyA: customerPhone,
            partyB: shortCode,
            description: description,
            initiatedBy: userId,
            requestPayload: {request: persistedPayload},
            mpesaTimestamp: timestamp,
        })
    } catch (e) {
        if (e.name === "SequelizeUniqueConstraintError") {
            const existingPayment = await Payment.findOne({
                where: {idempotencyKey: idempotencyKey}
            })

            if (existingPayment) {
                const handler = stkHandlers?.[existingPayment.status] ?? stkHandlers.FAILED
                return handler(existingPayment)
            }
        }
        throw e
    }
    try {
        const res = await darajaRequest({method, url, data})
        const success = res?.ResponseCode === "0"


        if (!success) {
            await payment.update({
                status: "FAILED",
                resultCode: res.ResponseCode,
                resultDescription: res.ResponseDescription,
                requestPayload: {request: persistedPayload, response: res,},
            })
            return payment
        }

        await payment.update({
            status: "SUBMITTED",
            checkoutRequestId: res.CheckoutRequestID,
            merchantRequestId: res.MerchantRequestID,
            resultCode: res.ResponseCode,
            resultDescription: res.ResponseDescription,
            requestPayload: {request: persistedPayload, response: res},
        })
        return payment
    } catch (e) {
        await payment.update({
            status: "FAILED", resultDescription: e.message, requestPayload: {request: persistedPayload},
        })
        throw e
    }
}
