import "dotenv/config.js"
import axios from "axios";
import {errorResponse, successResponse} from "../../utils/response.js";
import redisClient from "../../utils/redisClient.js";

export const getAccessToken = async (req, res) => {

    const cachedToken = await redisClient.get("mpesa:access_token")

    if (cachedToken) {
        return successResponse(res, cachedToken, "Token from cache", 200)
    }

    const lock = await redisClient.set("mpesa:access_token:lock", "1", {NX: true, EX: 60})

    // if lock fails try fetch cache token again
    if (!lock) {
        const retryToken = await redisClient.get("mpesa:access_token")
        if (retryToken) {
            return successResponse(res, retryToken, "Token fetched successfully after retry", 200)
        }

        return errorResponse(res, "Token is being generated by another user. Wait or try again later.", 429)
    }

    try {
        // TODO: use aws secrets for consumer key and secrets
        // obtain required variables to generate auth token
        const BASE_URL = process.env.MPESA_BASE_URL
        const URL = `${BASE_URL}/oauth/v1/generate?grant_type=client_credentials`
        // generate basic auth string
        const auth = Buffer.from(
            `${process.env.MPESA_CONSUMER_KEY}:${process.env.MPESA_CONSUMER_SECRET}`
        ).toString('base64')
        const response = await axios.get(URL, {
            headers: {
                Authorization: `Basic ${auth}`
            }
        })

        const token = response.data.access_token
        const expiresIn = response.data.expires_in

        // set newly fetched token in redis
        await redisClient.set("mpesa:access_token", token, {EX: expiresIn - 60})

        // release lock
        await redisClient.del("mpesa:access_token:lock")

        return successResponse(
            res,
            response.data,
            "Access token generated",
            response.status
        );
    } catch (e) {
        // CLean up lock if an error occurs
        await redisClient.del("mpesa:access_token:lock")
        return errorResponse(res, e.message, e.statusCode)
    }
}

